package jbo.ecr;

import java.lang.String;

/**
* 校验规则配置表 - JBO命名常量类<br><br>
* Note: This file is generated by ADE tools, <em>dont</em> modify it.<br>

*/
public interface ECR_VALIDATE_LIBRARY{
	/**
	* 校验规则配置表<br><br>
	* 代表本类映射的BizObjectClass
	*/
	public static final String CLASS_NAME = "jbo.ecr.ECR_VALIDATE_LIBRARY";
	/**
	* 规则编号 STRING(20)<br>
	*/
	public static final String RULENO = "RULENO";
	/**
	* 信息记录类型/报文类型 STRING(3)<br>
	*/
	public static final String INFRECTYPE = "INFRECTYPE";
	/**
	* 规则语句 STRING(2000)<br>
	*/
	public static final String RULESQL = "RULESQL";
	/**
	* 应用类别 STRING(2)<br>
	*/
	public static final String APPLICATIONCODE = "APPLICATIONCODE";
	/**
	* 状态 STRING(2)<br>
	*/
	public static final String STATUS = "STATUS";
	/**
	* 登记日期 STRING(10)<br>
	*/
	public static final String INPUTDATE = "INPUTDATE";
	/**
	* 更新日期 STRING(10)<br>
	*/
	public static final String UPDATEDATE = "UPDATEDATE";
	/**
	* 扩展字段1 STRING(30)<br>
	*/
	public static final String EXTEND1 = "EXTEND1";
	/**
	* 扩展字段2 STRING(30)<br>
	*/
	public static final String EXTEND2 = "EXTEND2";
	/**
	* 扩展字段3 STRING(30)<br>
	*/
	public static final String EXTEND3 = "EXTEND3";
}